// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Audit(arg1) {
  return window['go']['main']['App']['Audit'](arg1);
}

export function Backup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Backup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BuddyList() {
  return window['go']['main']['App']['BuddyList']();
}

export function BuddyRemove(arg1, arg2) {
  return window['go']['main']['App']['BuddyRemove'](arg1, arg2);
}

export function BuddyStatus(arg1) {
  return window['go']['main']['App']['BuddyStatus'](arg1);
}

export function CircleAdd(arg1, arg2) {
  return window['go']['main']['App']['CircleAdd'](arg1, arg2);
}

export function CircleList() {
  return window['go']['main']['App']['CircleList']();
}

export function CircleRemove(arg1) {
  return window['go']['main']['App']['CircleRemove'](arg1);
}

export function ConfigInit() {
  return window['go']['main']['App']['ConfigInit']();
}

export function ConfigShow() {
  return window['go']['main']['App']['ConfigShow']();
}

export function Dashboard(arg1) {
  return window['go']['main']['App']['Dashboard'](arg1);
}

export function DeletePassword() {
  return window['go']['main']['App']['DeletePassword']();
}

export function Diff(arg1) {
  return window['go']['main']['App']['Diff'](arg1);
}

export function Doctor(arg1, arg2) {
  return window['go']['main']['App']['Doctor'](arg1, arg2);
}

export function Export(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Export'](arg1, arg2, arg3, arg4);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetServeStatus() {
  return window['go']['main']['App']['GetServeStatus']();
}

export function Import(arg1, arg2) {
  return window['go']['main']['App']['Import'](arg1, arg2);
}

export function Init(arg1) {
  return window['go']['main']['App']['Init'](arg1);
}

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function InviteEmail(arg1, arg2) {
  return window['go']['main']['App']['InviteEmail'](arg1, arg2);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function IsWatching() {
  return window['go']['main']['App']['IsWatching']();
}

export function Join(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Join'](arg1, arg2, arg3, arg4);
}

export function JoinEmail(arg1, arg2) {
  return window['go']['main']['App']['JoinEmail'](arg1, arg2);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function ManifestPull(arg1, arg2) {
  return window['go']['main']['App']['ManifestPull'](arg1, arg2);
}

export function Passwd(arg1, arg2) {
  return window['go']['main']['App']['Passwd'](arg1, arg2);
}

export function Prune(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Prune'](arg1, arg2, arg3, arg4, arg5);
}

export function Rebalance(arg1) {
  return window['go']['main']['App']['Rebalance'](arg1);
}

export function Recover(arg1, arg2) {
  return window['go']['main']['App']['Recover'](arg1, arg2);
}

export function Restore(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Restore'](arg1, arg2, arg3, arg4, arg5);
}

export function Scrub() {
  return window['go']['main']['App']['Scrub']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function ShowPhrase() {
  return window['go']['main']['App']['ShowPhrase']();
}

export function StartServe(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServe'](arg1, arg2, arg3);
}

export function StartWatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartWatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopServe() {
  return window['go']['main']['App']['StopServe']();
}

export function StopWatch() {
  return window['go']['main']['App']['StopWatch']();
}

export function Storage(arg1) {
  return window['go']['main']['App']['Storage'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function Versions(arg1) {
  return window['go']['main']['App']['Versions'](arg1);
}
