// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {buddy} from '../models';
import {circle} from '../models';
import {main} from '../models';
import {protocol} from '../models';
import {rebalance} from '../models';
import {scrub} from '../models';

export function Audit(arg1:string):Promise<api.AuditResult>;

export function Backup(arg1:string,arg2:number,arg3:string,arg4:number,arg5:boolean,arg6:Array<string>):Promise<api.BackupResult>;

export function BuddyList():Promise<Array<buddy.Entry>>;

export function BuddyRemove(arg1:string,arg2:boolean):Promise<void>;

export function BuddyStatus(arg1:number):Promise<Array<api.BuddyStatusEntry>>;

export function CircleAdd(arg1:string,arg2:string):Promise<circle.Circle>;

export function CircleList():Promise<Array<circle.Circle>>;

export function CircleRemove(arg1:string):Promise<void>;

export function ConfigInit():Promise<string>;

export function ConfigShow():Promise<main.ConfigShowResult>;

export function Dashboard(arg1:string):Promise<api.DashboardResult>;

export function DeletePassword():Promise<void>;

export function Diff(arg1:number):Promise<Array<api.DiffChange>>;

export function Doctor(arg1:string,arg2:boolean):Promise<api.DoctorResult>;

export function Export(arg1:string,arg2:number,arg3:string,arg4:string):Promise<api.ExportResult>;

export function GetLanguage():Promise<string>;

export function GetServeStatus():Promise<main.ServeStatus>;

export function Import(arg1:string,arg2:string):Promise<api.ImportResult>;

export function Init(arg1:api.InitParams):Promise<api.InitResult>;

export function Invite(arg1:number):Promise<api.InviteResult>;

export function InviteEmail(arg1:string,arg2:string):Promise<api.InviteEmailResult>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function IsWatching():Promise<boolean>;

export function Join(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function JoinEmail(arg1:Array<number>,arg2:string):Promise<main.JoinEmailResult>;

export function ListFiles(arg1:boolean):Promise<Array<protocol.ManifestEntry>>;

export function Lock():Promise<void>;

export function ManifestPull(arg1:string,arg2:string):Promise<api.ManifestPullResult>;

export function Passwd(arg1:string,arg2:string):Promise<void>;

export function Prune(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:string):Promise<api.PruneResult>;

export function Rebalance():Promise<rebalance.Result>;

export function Recover(arg1:string,arg2:string):Promise<api.RecoverResult>;

export function Restore(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<api.RestoreResult>;

export function Scrub():Promise<scrub.Report>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function ShowPhrase():Promise<string>;

export function StartServe(arg1:number,arg2:number,arg3:string):Promise<main.ServeStatus>;

export function StartWatch(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:number,arg7:boolean):Promise<void>;

export function StopServe():Promise<void>;

export function StopWatch():Promise<void>;

export function Storage(arg1:string):Promise<api.StorageStats>;

export function Unlock(arg1:string):Promise<void>;

export function Versions(arg1:string):Promise<Array<protocol.ManifestEntry>>;
